# Generated by Django 2.2.2 on 2019-09-27 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dcodex", "0003_auto_20190920_1333"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manuscript",
            options={"ordering": ["siglum", "name"]},
        ),
    ]
