# Generated by Django 2.2.2 on 2020-05-26 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dcodex", "0005_auto_20200526_1559"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="members",
        ),
    ]
