# Generated by Django 2.2.2 on 2020-05-26 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dcodex", "0006_remove_group_members"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Membership",
        ),
    ]
