# Generated by Django 2.2.2 on 2020-05-26 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dcodex", "0008_auto_20200526_2053"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "groupbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dcodex.GroupBase",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("dcodex.groupbase",),
        ),
    ]
