# Generated by Django 2.2.2 on 2020-05-26 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dcodex", "0010_groupmembershipbase"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupMembershipAll",
            fields=[
                (
                    "groupmembershipbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dcodex.GroupMembershipBase",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("dcodex.groupmembershipbase",),
        ),
        migrations.CreateModel(
            name="GroupMembershipRange",
            fields=[
                (
                    "groupmembershipbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dcodex.GroupMembershipBase",
                    ),
                ),
                (
                    "end_verse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="end_verse",
                        to="dcodex.Verse",
                    ),
                ),
                (
                    "start_verse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="start_verse",
                        to="dcodex.Verse",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("dcodex.groupmembershipbase",),
        ),
    ]
