# Generated by Django 2.2.2 on 2020-05-27 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dcodex", "0013_auto_20200527_2210"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GroupMembershipRange",
        ),
    ]
