# Generated by Django 2.2.2 on 2020-05-27 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dcodex", "0014_delete_groupmembershiprange"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GroupMembershipAll",
        ),
    ]
