# Generated by Django 2.2.2 on 2020-05-28 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dcodex", "0019_auto_20200527_2213"),
    ]

    operations = [
        migrations.AddField(
            model_name="affiliationbase",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="A descriptive string for this affilitation.",
                max_length=200,
            ),
        ),
    ]
