# Generated by Django 2.2.2 on 2020-05-29 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dcodex", "0020_affiliationbase_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AffiliationVerses",
            fields=[
                (
                    "affiliationbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dcodex.AffiliationBase",
                    ),
                ),
                (
                    "verses",
                    models.ManyToManyField(
                        help_text="All the verses where this affiliation object is active.",
                        related_name="affiliation_verses",
                        to="dcodex.Verse",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("dcodex.affiliationbase",),
        ),
    ]
