# Generated by Django 3.0.8 on 2020-08-03 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dcodex", "0021_affiliationverses"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="family",
            options={"verbose_name_plural": "Families"},
        ),
    ]
