# Generated by Django 3.0.8 on 2020-08-09 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dcodex", "0022_auto_20200803_1646"),
    ]

    operations = [
        migrations.CreateModel(
            name="AffiliationExcludeVerses",
            fields=[
                (
                    "affiliationbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dcodex.AffiliationBase",
                    ),
                ),
                (
                    "verses",
                    models.ManyToManyField(
                        help_text="All the verses where this affiliation object is inactive.",
                        related_name="affiliation_exclude_verses",
                        to="dcodex.Verse",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("dcodex.affiliationbase",),
        ),
    ]
