# Generated by Django 3.0.8 on 2020-08-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dcodex", "0023_affiliationexcludeverses"),
    ]

    operations = [
        migrations.RenameField(
            model_name="affiliationexcludeverses",
            old_name="verses",
            new_name="exclude",
        ),
        migrations.AddField(
            model_name="affiliationrange",
            name="exclude",
            field=models.ManyToManyField(
                help_text="All the verses in this range where this affiliation object is actually inactive.",
                related_name="affiliationrange_exclude_verses",
                to="dcodex.Verse",
            ),
        ),
    ]
