# Generated by Django 3.0.8 on 2020-10-04 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("dcodex", "0025_auto_20200809_1536"),
    ]

    operations = [
        migrations.CreateModel(
            name="Markup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_dcodex.markup_set+",
                        to="contenttypes.ContentType",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="StandardMarkup",
            fields=[
                (
                    "markup_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dcodex.Markup",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("dcodex.markup",),
        ),
        migrations.AddField(
            model_name="versetranscriptionbase",
            name="markup",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The markup class for this transcription.",
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="dcodex.Markup",
            ),
        ),
    ]
