# Generated by Django 3.0.8 on 2020-10-04 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dcodex", "0026_auto_20201004_1045"),
    ]

    operations = [
        migrations.AddField(
            model_name="manuscript",
            name="markup",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The default markup class for this manuscript.",
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="dcodex.Markup",
            ),
        ),
    ]
