# Generated by Django 3.0.11 on 2020-11-23 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("imagedeck", "0009_auto_20201122_2300"),
        ("dcodex", "0030_auto_20201122_2300"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folioref",
            name="deck_membership",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="imagedeck.DeckMembership",
            ),
        ),
    ]
