# Generated by Django 3.1.3 on 2020-12-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dcodex", "0033_simplearabicmarkup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manuscript",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="A descriptive name for this manuscript.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="siglum",
            field=models.CharField(
                blank=True,
                help_text="A unique short string for this manuscript.",
                max_length=255,
            ),
        ),
    ]
