# Generated by Django 3.1.3 on 2021-06-20 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dcodex", "0035_auto_20210216_0331"),
    ]

    operations = [
        migrations.CreateModel(
            name="MinimalMarkup",
            fields=[
                (
                    "markup_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dcodex.markup",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("dcodex.markup",),
        ),
    ]
