# Generated by Django 3.2.9 on 2021-11-20 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex', '0036_minimalmarkup'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonLatinMarkup',
            fields=[
                ('markup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dcodex.markup')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('dcodex.markup',),
        ),
    ]
