# Generated by Django 3.2.9 on 2021-11-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex', '0037_nonlatinmarkup'),
    ]

    operations = [
        migrations.AddField(
            model_name='markup',
            name='punctuation_tokens',
            field=models.BooleanField(default=False, help_text='Whether or not punctuation markers can be tokens.'),
        ),
    ]
