# Generated by Django 3.2.9 on 2021-11-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex', '0038_markup_punctuation_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonlatinmarkup',
            name='number_tokens',
            field=models.BooleanField(default=True, help_text='Whether or not numbers can be tokens.'),
        ),
    ]
