# Generated by Django 3.2.9 on 2022-04-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex', '0039_nonlatinmarkup_number_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versetranscriptionbase',
            name='transcription',
            field=models.TextField(help_text='The unnormalized text of this transcription.'),
        ),
    ]
