# Generated by Django 3.2.13 on 2022-11-22 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex', '0040_alter_versetranscriptionbase_transcription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manuscript',
            options={'ordering': ['rank', 'siglum', 'name']},
        ),
        migrations.AddField(
            model_name='manuscript',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
