# Generated by Django 3.2.13 on 2023-07-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex', '0041_auto_20221122_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='origin_date_earliest',
            field=models.IntegerField(blank=True, default=None, help_text='The earliest possible date for the origin of the manuscript.', null=True),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='origin_date_latest',
            field=models.IntegerField(blank=True, default=None, help_text='The latest possible date for the origin of the manuscript.', null=True),
        ),
    ]
